// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_BLUETOOTH_LOW_ENERGY_API_G_H_
#define PIGEON_BLUETOOTH_LOW_ENERGY_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace bluetooth_low_energy_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class BluetoothLowEnergyStateArgs {
  kUnknown = 0,
  kUnsupported = 1,
  kDisabled = 2,
  kOff = 3,
  kOn = 4
};

enum class AdvertisementTypeArgs {
  kConnectableUndirected = 0,
  kConnectableDirected = 1,
  kScannableUndirected = 2,
  kNonConnectableUndirected = 3,
  kScanResponse = 4,
  kExtended = 5
};

enum class ConnectionStateArgs {
  kDisconnected = 0,
  kConnected = 1
};

// Windows の `DevicePairingProtectionLevel` をそのまま写したもの。
//
// pair で要求する保護レベル。装置側のセキュリティ要求(暗号化必須の
// GATT 等)に合わせてセントラル側からも同じ水準を要求するための口。
// `defaultLevel` は OS に適切なレベルを選ばせる。
enum class DevicePairingProtectionLevelArgs {
  kDefaultLevel = 0,
  kNone = 1,
  kEncryption = 2,
  kEncryptionAndAuthentication = 3
};

// Windows の `DevicePairingResultStatus` をそのまま写したもの。
//
// 文字列へ潰さず列挙で返すことで、呼び出し側が
// 「利用者がキャンセルした」「認証がタイムアウトした」「拒否された」を
// 区別できる。
enum class DevicePairingResultStatusArgs {
  kPaired = 0,
  kNotReadyToPair = 1,
  kNotPaired = 2,
  kAlreadyPaired = 3,
  kConnectionRejected = 4,
  kTooManyConnections = 5,
  kHardwareFailure = 6,
  kAuthenticationTimeout = 7,
  kAuthenticationNotAllowed = 8,
  kAuthenticationFailure = 9,
  kNoSupportedProfiles = 10,
  kProtectionLevelCouldNotBeMet = 11,
  kAccessDenied = 12,
  kInvalidCeremonyData = 13,
  kPairingCanceled = 14,
  kOperationAlreadyInProgress = 15,
  kRequiredHandlerNotRegistered = 16,
  kRejectedByHandler = 17,
  kRemoteDeviceHasAssociation = 18,
  kFailed = 19
};

enum class GATTCharacteristicPropertyArgs {
  kRead = 0,
  kWrite = 1,
  kWriteWithoutResponse = 2,
  kNotify = 3,
  kIndicate = 4
};

enum class GATTCharacteristicWriteTypeArgs {
  kWithResponse = 0,
  kWithoutResponse = 1
};

enum class GATTCharacteristicNotifyStateArgs {
  kNone = 0,
  kNotify = 1,
  kIndicate = 2
};

enum class GATTProtectionLevelArgs {
  kPlain = 0,
  kAuthenticationRequired = 1,
  kEntryptionRequired = 2,
  kEncryptionAndAuthenticationRequired = 3
};

enum class GATTProtocolErrorArgs {
  kInvalidHandle = 0,
  kReadNotPermitted = 1,
  kWriteNotPermitted = 2,
  kInvalidPDU = 3,
  kInsufficientAuthentication = 4,
  kRequestNotSupported = 5,
  kInvalidOffset = 6,
  kInsufficientAuthorization = 7,
  kPrepareQueueFull = 8,
  kAttributeNotFound = 9,
  kAttributeNotLong = 10,
  kInsufficientEncryptionKeySize = 11,
  kInvalidAttributeValueLength = 12,
  kUnlikelyError = 13,
  kInsufficientEncryption = 14,
  kUnsupportedGroupType = 15,
  kInsufficientResources = 16
};

enum class CacheModeArgs {
  kCached = 0,
  kUncached = 1
};


// Generated class from Pigeon that represents data sent in messages.
class ManufacturerSpecificDataArgs {
 public:
  // Constructs an object setting all fields.
  explicit ManufacturerSpecificDataArgs(
    int64_t id_args,
    const std::vector<uint8_t>& data_args);

  int64_t id_args() const;
  void set_id_args(int64_t value_arg);

  const std::vector<uint8_t>& data_args() const;
  void set_data_args(const std::vector<uint8_t>& value_arg);

 private:
  static ManufacturerSpecificDataArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t id_args_;
  std::vector<uint8_t> data_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class AdvertisementArgs {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit AdvertisementArgs(
    const flutter::EncodableList& service_u_u_i_ds_args,
    const flutter::EncodableMap& service_data_args,
    const flutter::EncodableList& manufacturer_specific_data_args);

  // Constructs an object setting all fields.
  explicit AdvertisementArgs(
    const std::string* name_args,
    const flutter::EncodableList& service_u_u_i_ds_args,
    const flutter::EncodableMap& service_data_args,
    const flutter::EncodableList& manufacturer_specific_data_args);

  const std::string* name_args() const;
  void set_name_args(const std::string_view* value_arg);
  void set_name_args(std::string_view value_arg);

  const flutter::EncodableList& service_u_u_i_ds_args() const;
  void set_service_u_u_i_ds_args(const flutter::EncodableList& value_arg);

  const flutter::EncodableMap& service_data_args() const;
  void set_service_data_args(const flutter::EncodableMap& value_arg);

  const flutter::EncodableList& manufacturer_specific_data_args() const;
  void set_manufacturer_specific_data_args(const flutter::EncodableList& value_arg);

 private:
  static AdvertisementArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> name_args_;
  flutter::EncodableList service_u_u_i_ds_args_;
  flutter::EncodableMap service_data_args_;
  flutter::EncodableList manufacturer_specific_data_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class CentralArgs {
 public:
  // Constructs an object setting all fields.
  explicit CentralArgs(int64_t address_args);

  int64_t address_args() const;
  void set_address_args(int64_t value_arg);

 private:
  static CentralArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t address_args_;
};


// OS が関連付け(ペアリング)を保持している装置。
//
// 広告(スキャン)ではなく、OS の関連付けの一覧から得られる。
//
// Generated class from Pigeon that represents data sent in messages.
class PairedPeripheralArgs {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PairedPeripheralArgs(
    int64_t address_args,
    const std::string& id_args);

  // Constructs an object setting all fields.
  explicit PairedPeripheralArgs(
    int64_t address_args,
    const std::string* name_args,
    const std::string& id_args);

  int64_t address_args() const;
  void set_address_args(int64_t value_arg);

  const std::string* name_args() const;
  void set_name_args(const std::string_view* value_arg);
  void set_name_args(std::string_view value_arg);

  // `DeviceInformation.Id`(関連付けの識別子)。アドレスと違い、
  // OS がこの装置を指すために使う正式な ID。
  const std::string& id_args() const;
  void set_id_args(std::string_view value_arg);

 private:
  static PairedPeripheralArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t address_args_;
  std::optional<std::string> name_args_;
  std::string id_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class PeripheralArgs {
 public:
  // Constructs an object setting all fields.
  explicit PeripheralArgs(int64_t address_args);

  int64_t address_args() const;
  void set_address_args(int64_t value_arg);

 private:
  static PeripheralArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t address_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class GATTDescriptorArgs {
 public:
  // Constructs an object setting all fields.
  explicit GATTDescriptorArgs(
    int64_t handle_args,
    const std::string& uuid_args);

  int64_t handle_args() const;
  void set_handle_args(int64_t value_arg);

  const std::string& uuid_args() const;
  void set_uuid_args(std::string_view value_arg);

 private:
  static GATTDescriptorArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t handle_args_;
  std::string uuid_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class GATTCharacteristicArgs {
 public:
  // Constructs an object setting all fields.
  explicit GATTCharacteristicArgs(
    int64_t handle_args,
    const std::string& uuid_args,
    const flutter::EncodableList& property_numbers_args,
    const flutter::EncodableList& descriptors_args);

  int64_t handle_args() const;
  void set_handle_args(int64_t value_arg);

  const std::string& uuid_args() const;
  void set_uuid_args(std::string_view value_arg);

  const flutter::EncodableList& property_numbers_args() const;
  void set_property_numbers_args(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& descriptors_args() const;
  void set_descriptors_args(const flutter::EncodableList& value_arg);

 private:
  static GATTCharacteristicArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t handle_args_;
  std::string uuid_args_;
  flutter::EncodableList property_numbers_args_;
  flutter::EncodableList descriptors_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class GATTServiceArgs {
 public:
  // Constructs an object setting all fields.
  explicit GATTServiceArgs(
    int64_t handle_args,
    const std::string& uuid_args,
    bool is_primary_args,
    const flutter::EncodableList& included_services_args,
    const flutter::EncodableList& characteristics_args);

  int64_t handle_args() const;
  void set_handle_args(int64_t value_arg);

  const std::string& uuid_args() const;
  void set_uuid_args(std::string_view value_arg);

  bool is_primary_args() const;
  void set_is_primary_args(bool value_arg);

  const flutter::EncodableList& included_services_args() const;
  void set_included_services_args(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& characteristics_args() const;
  void set_characteristics_args(const flutter::EncodableList& value_arg);

 private:
  static GATTServiceArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t handle_args_;
  std::string uuid_args_;
  bool is_primary_args_;
  flutter::EncodableList included_services_args_;
  flutter::EncodableList characteristics_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class MutableGATTDescriptorArgs {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MutableGATTDescriptorArgs(
    int64_t hash_code_args,
    const std::string& uuid_args);

  // Constructs an object setting all fields.
  explicit MutableGATTDescriptorArgs(
    int64_t hash_code_args,
    const std::string& uuid_args,
    const std::vector<uint8_t>* value_args,
    const GATTProtectionLevelArgs* read_protection_level_args,
    const GATTProtectionLevelArgs* write_protection_level_args);

  int64_t hash_code_args() const;
  void set_hash_code_args(int64_t value_arg);

  const std::string& uuid_args() const;
  void set_uuid_args(std::string_view value_arg);

  const std::vector<uint8_t>* value_args() const;
  void set_value_args(const std::vector<uint8_t>* value_arg);
  void set_value_args(const std::vector<uint8_t>& value_arg);

  const GATTProtectionLevelArgs* read_protection_level_args() const;
  void set_read_protection_level_args(const GATTProtectionLevelArgs* value_arg);
  void set_read_protection_level_args(const GATTProtectionLevelArgs& value_arg);

  const GATTProtectionLevelArgs* write_protection_level_args() const;
  void set_write_protection_level_args(const GATTProtectionLevelArgs* value_arg);
  void set_write_protection_level_args(const GATTProtectionLevelArgs& value_arg);

 private:
  static MutableGATTDescriptorArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t hash_code_args_;
  std::string uuid_args_;
  std::optional<std::vector<uint8_t>> value_args_;
  std::optional<GATTProtectionLevelArgs> read_protection_level_args_;
  std::optional<GATTProtectionLevelArgs> write_protection_level_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class MutableGATTCharacteristicArgs {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MutableGATTCharacteristicArgs(
    int64_t hash_code_args,
    const std::string& uuid_args,
    const flutter::EncodableList& property_numbers_args,
    const flutter::EncodableList& descriptors_args);

  // Constructs an object setting all fields.
  explicit MutableGATTCharacteristicArgs(
    int64_t hash_code_args,
    const std::string& uuid_args,
    const std::vector<uint8_t>* value_args,
    const flutter::EncodableList& property_numbers_args,
    const GATTProtectionLevelArgs* read_protection_level_args,
    const GATTProtectionLevelArgs* write_protection_level_args,
    const flutter::EncodableList& descriptors_args);

  int64_t hash_code_args() const;
  void set_hash_code_args(int64_t value_arg);

  const std::string& uuid_args() const;
  void set_uuid_args(std::string_view value_arg);

  const std::vector<uint8_t>* value_args() const;
  void set_value_args(const std::vector<uint8_t>* value_arg);
  void set_value_args(const std::vector<uint8_t>& value_arg);

  const flutter::EncodableList& property_numbers_args() const;
  void set_property_numbers_args(const flutter::EncodableList& value_arg);

  const GATTProtectionLevelArgs* read_protection_level_args() const;
  void set_read_protection_level_args(const GATTProtectionLevelArgs* value_arg);
  void set_read_protection_level_args(const GATTProtectionLevelArgs& value_arg);

  const GATTProtectionLevelArgs* write_protection_level_args() const;
  void set_write_protection_level_args(const GATTProtectionLevelArgs* value_arg);
  void set_write_protection_level_args(const GATTProtectionLevelArgs& value_arg);

  const flutter::EncodableList& descriptors_args() const;
  void set_descriptors_args(const flutter::EncodableList& value_arg);

 private:
  static MutableGATTCharacteristicArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t hash_code_args_;
  std::string uuid_args_;
  std::optional<std::vector<uint8_t>> value_args_;
  flutter::EncodableList property_numbers_args_;
  std::optional<GATTProtectionLevelArgs> read_protection_level_args_;
  std::optional<GATTProtectionLevelArgs> write_protection_level_args_;
  flutter::EncodableList descriptors_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class MutableGATTServiceArgs {
 public:
  // Constructs an object setting all fields.
  explicit MutableGATTServiceArgs(
    int64_t hash_code_args,
    const std::string& uuid_args,
    bool is_primary_args,
    const flutter::EncodableList& included_services_args,
    const flutter::EncodableList& characteristics_args);

  int64_t hash_code_args() const;
  void set_hash_code_args(int64_t value_arg);

  const std::string& uuid_args() const;
  void set_uuid_args(std::string_view value_arg);

  bool is_primary_args() const;
  void set_is_primary_args(bool value_arg);

  const flutter::EncodableList& included_services_args() const;
  void set_included_services_args(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& characteristics_args() const;
  void set_characteristics_args(const flutter::EncodableList& value_arg);

 private:
  static MutableGATTServiceArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t hash_code_args_;
  std::string uuid_args_;
  bool is_primary_args_;
  flutter::EncodableList included_services_args_;
  flutter::EncodableList characteristics_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class GATTReadRequestArgs {
 public:
  // Constructs an object setting all fields.
  explicit GATTReadRequestArgs(
    int64_t id_args,
    int64_t offset_args,
    int64_t length_args);

  int64_t id_args() const;
  void set_id_args(int64_t value_arg);

  int64_t offset_args() const;
  void set_offset_args(int64_t value_arg);

  int64_t length_args() const;
  void set_length_args(int64_t value_arg);

 private:
  static GATTReadRequestArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t id_args_;
  int64_t offset_args_;
  int64_t length_args_;
};


// Generated class from Pigeon that represents data sent in messages.
class GATTWriteRequestArgs {
 public:
  // Constructs an object setting all fields.
  explicit GATTWriteRequestArgs(
    int64_t id_args,
    int64_t offset_args,
    const std::vector<uint8_t>& value_args,
    const GATTCharacteristicWriteTypeArgs& type_args);

  int64_t id_args() const;
  void set_id_args(int64_t value_arg);

  int64_t offset_args() const;
  void set_offset_args(int64_t value_arg);

  const std::vector<uint8_t>& value_args() const;
  void set_value_args(const std::vector<uint8_t>& value_arg);

  const GATTCharacteristicWriteTypeArgs& type_args() const;
  void set_type_args(const GATTCharacteristicWriteTypeArgs& value_arg);

 private:
  static GATTWriteRequestArgs FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CentralManagerHostApi;
  friend class CentralManagerFlutterApi;
  friend class PeripheralManagerHostApi;
  friend class PeripheralManagerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t id_args_;
  int64_t offset_args_;
  std::vector<uint8_t> value_args_;
  GATTCharacteristicWriteTypeArgs type_args_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class CentralManagerHostApi {
 public:
  CentralManagerHostApi(const CentralManagerHostApi&) = delete;
  CentralManagerHostApi& operator=(const CentralManagerHostApi&) = delete;
  virtual ~CentralManagerHostApi() {}
  virtual void Initialize(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual ErrorOr<BluetoothLowEnergyStateArgs> GetState() = 0;
  virtual std::optional<FlutterError> StartDiscovery(const flutter::EncodableList& service_u_u_i_ds_args) = 0;
  virtual std::optional<FlutterError> StopDiscovery() = 0;
  virtual void Connect(
    int64_t address_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual std::optional<FlutterError> Disconnect(int64_t address_args) = 0;
  virtual ErrorOr<int64_t> GetMTU(int64_t address_args) = 0;
  virtual void GetServices(
    int64_t address_args,
    const CacheModeArgs& mode_args,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  virtual void GetIncludedServices(
    int64_t address_args,
    int64_t handle_args,
    const CacheModeArgs& mode_args,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  virtual void GetCharacteristics(
    int64_t address_args,
    int64_t handle_args,
    const CacheModeArgs& mode_args,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  virtual void GetDescriptors(
    int64_t address_args,
    int64_t handle_args,
    const CacheModeArgs& mode_args,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  virtual void ReadCharacteristic(
    int64_t address_args,
    int64_t handle_args,
    const CacheModeArgs& mode_args,
    std::function<void(ErrorOr<std::vector<uint8_t>> reply)> result) = 0;
  virtual void WriteCharacteristic(
    int64_t address_args,
    int64_t handle_args,
    const std::vector<uint8_t>& value_args,
    const GATTCharacteristicWriteTypeArgs& type_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetCharacteristicNotifyState(
    int64_t address_args,
    int64_t handle_args,
    const GATTCharacteristicNotifyStateArgs& state_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // 特性への無線通信に要求する GATT セキュリティ
  // (`GattCharacteristic.ProtectionLevel`)を設定する。
  //
  // 設定後にその特性へ read/write すると、スタックは要求水準を満たす
  // リンク(暗号化等)を操作の前提として確立しようとする。装置側の
  // セキュリティ要求と一致させることで、ATT エラー(0x0F 等)を起点と
  // した事後の再試行ではなく、OS 主導の事前確立に切り替えられる。
  virtual std::optional<FlutterError> SetCharacteristicProtectionLevel(
    int64_t address_args,
    int64_t handle_args,
    const GATTProtectionLevelArgs& level_args) = 0;
  virtual void ReadDescriptor(
    int64_t address_args,
    int64_t handle_args,
    const CacheModeArgs& mode_args,
    std::function<void(ErrorOr<std::vector<uint8_t>> reply)> result) = 0;
  virtual void WriteDescriptor(
    int64_t address_args,
    int64_t handle_args,
    const std::vector<uint8_t>& value_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // ペアリング(暗号化リンクの確立)を開始し、結果が出るまで待つ。
  //
  // 保護された属性は、リンクが暗号化されていないと読み書きできない。
  // ボンディングしない装置では鍵が保存されないため、**接続ごとに**
  // これを済ませてから初期読み出しへ進む必要がある。
  //
  // デスクトップでは同意は必ずシステムダイアログで行われ、アプリからは
  // 抑止できない(Microsoft の文書と実測の両方で確認)。アプリ側の
  // PairingRequested ハンドラは、ConfirmOnly を受理するために常に登録する
  // (登録しないと RequiredHandlerNotRegistered / RejectedByHandler で
  // 失敗する)。つまり「自動承認するか」という選択肢は存在しない。
  //
  // 失敗を例外にせず結果として返すので、キャンセル・タイムアウト・拒否を
  // 呼び出し側で区別できる。
  //
  // [protectionLevelArgs] は要求する保護レベル。装置側のセキュリティ要求に
  // 合わせて指定する(未ペアリング機器の `Pairing().ProtectionLevel()` は
  // 「現在の水準 = None」を返すだけで要求水準ではないため、ここで明示する)。
  virtual void Pair(
    int64_t address_args,
    const DevicePairingProtectionLevelArgs& protection_level_args,
    std::function<void(ErrorOr<DevicePairingResultStatusArgs> reply)> result) = 0;
  // OS が保持しているペアリング(関連付け)を解除する。接続は不要。
  virtual void Unpair(
    int64_t address_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // OS がこの装置をペアリング済みとみなしているか。接続は不要。
  //
  // WinRT はプラットフォームスレッド(STA)でのブロック待ちを禁じているため、
  // 同期メソッドにはできない(`.get()` が `!is_sta_thread()` で落ちる)。
  virtual void IsPaired(
    int64_t address_args,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // OS が関連付け(ペアリング)を保持している装置を列挙する。
  //
  // `BluetoothLEDevice.GetDeviceSelectorFromPairingState(true)` の AQS を
  // `DeviceInformation.FindAllAsync` に渡して得る。広告を待つ必要はなく、
  // 装置が圏外でも一覧には出る(接続できるかは別)。
  virtual void GetPairedPeripherals(std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // 関連付け済みの装置へ、その関連付け経由で接続する。
  //
  // connect はアドレスから装置オブジェクトを作る(`FromBluetoothAddressAsync`)
  // のに対し、こちらは OS が保持している関連付け(AssociationEndpoint)を
  // 引いて `FromIdAsync` で作る。ペアリング済み装置に対して OS が正式に
  // 用意している経路はこちら。
  //
  // 関連付けが無い装置ではエラーになる(先に pair が要る)。
  virtual void ConnectPaired(
    int64_t address_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // `GattSession.MaintainConnection` 方式で接続を開始する。
  //
  // connect(GATT 操作起点)の接続待ちは OS 内部で 7 秒固定・キャンセル
  // 不可(公式文書)。こちらは MaintainConnection を true にして
  // 「デバイスが現れ次第 OS が接続する」を無期限で依頼し、**リンク確立を
  // 待たずに返る**。確立は onConnectionStateChanged(connected) で通知
  // されるため、待ち時間の上限と中断(disconnect = 参照解放で依頼ごと
  // 消える)は呼び出し側が管理する。
  //
  // true のままだとリンク断のたびに OS が自動で張り直すため、確立後は
  // setMaintainConnection(false) で戻すこと(再接続の主導権をアプリに残す)。
  virtual void ConnectMaintained(
    int64_t address_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // `GattSession.MaintainConnection` を設定する。
  // connectMaintained で確立した後に false へ戻す用途。
  // セッション未保持(未接続)の装置に対してはエラー。
  virtual std::optional<FlutterError> SetMaintainConnection(
    int64_t address_args,
    bool enable_args) = 0;

  // The codec used by CentralManagerHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `CentralManagerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    CentralManagerHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    CentralManagerHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  CentralManagerHostApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class CentralManagerFlutterApi {
 public:
  CentralManagerFlutterApi(flutter::BinaryMessenger* binary_messenger);
  CentralManagerFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnStateChanged(
    const BluetoothLowEnergyStateArgs& state_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDiscovered(
    const PeripheralArgs& peripheral_args,
    int64_t rssi_args,
    int64_t timestamp_args,
    const AdvertisementTypeArgs& type_args,
    const AdvertisementArgs& advertisement_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnConnectionStateChanged(
    const PeripheralArgs& peripheral_args,
    const ConnectionStateArgs& state_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnMTUChanged(
    const PeripheralArgs& peripheral_args,
    int64_t mtu_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCharacteristicNotified(
    const PeripheralArgs& peripheral_args,
    const GATTCharacteristicArgs& characteristic_args,
    const std::vector<uint8_t>& value_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // ネイティブ層の診断メッセージ。Dart 側の logger(info)へ中継する。
  //
  // ネイティブには独自のログ機構が無いため、調査時の観測値
  // (例: ペアリングの保護レベル・儀式の発火有無)はこの口で表出する。
  void OnLogged(
    const std::string& message_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class PeripheralManagerHostApi {
 public:
  PeripheralManagerHostApi(const PeripheralManagerHostApi&) = delete;
  PeripheralManagerHostApi& operator=(const PeripheralManagerHostApi&) = delete;
  virtual ~PeripheralManagerHostApi() {}
  virtual void Initialize(std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual ErrorOr<BluetoothLowEnergyStateArgs> GetState() = 0;
  virtual void AddService(
    const MutableGATTServiceArgs& service_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual std::optional<FlutterError> RemoveService(int64_t hash_code_args) = 0;
  virtual std::optional<FlutterError> StartAdvertising(const AdvertisementArgs& advertisement_args) = 0;
  virtual std::optional<FlutterError> StopAdvertising() = 0;
  virtual ErrorOr<int64_t> GetMaxNotificationSize(int64_t address_args) = 0;
  virtual std::optional<FlutterError> RespondReadRequestWithValue(
    int64_t id_args,
    const std::vector<uint8_t>& value_args) = 0;
  virtual std::optional<FlutterError> RespondReadRequestWithProtocolError(
    int64_t id_args,
    const GATTProtocolErrorArgs& error_args) = 0;
  virtual std::optional<FlutterError> RespondWriteRequest(int64_t id_args) = 0;
  virtual std::optional<FlutterError> RespondWriteRequestWithProtocolError(
    int64_t id_args,
    const GATTProtocolErrorArgs& error_args) = 0;
  virtual void NotifyValue(
    int64_t address_args,
    int64_t hash_code_args,
    const std::vector<uint8_t>& value_args,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by PeripheralManagerHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `PeripheralManagerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PeripheralManagerHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PeripheralManagerHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  PeripheralManagerHostApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class PeripheralManagerFlutterApi {
 public:
  PeripheralManagerFlutterApi(flutter::BinaryMessenger* binary_messenger);
  PeripheralManagerFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnStateChanged(
    const BluetoothLowEnergyStateArgs& state_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnMTUChanged(
    const CentralArgs& central_args,
    int64_t mtu_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCharacteristicReadRequest(
    const CentralArgs& central_args,
    int64_t hash_code_args,
    const GATTReadRequestArgs& request_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCharacteristicWriteRequest(
    const CentralArgs& central_args,
    int64_t hash_code_args,
    const GATTWriteRequestArgs& request_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCharacteristicSubscribedClientsChanged(
    int64_t hash_code_args,
    const flutter::EncodableList& centrals_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDescriptorReadRequest(
    const CentralArgs& central_args,
    int64_t hash_code_args,
    const GATTReadRequestArgs& request_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDescriptorWriteRequest(
    const CentralArgs& central_args,
    int64_t hash_code_args,
    const GATTWriteRequestArgs& request_args,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace bluetooth_low_energy_windows
#endif  // PIGEON_BLUETOOTH_LOW_ENERGY_API_G_H_
