// Autogenerated from Pigeon (v26.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum BluetoothLowEnergyStateArgs {
  unknown,
  unsupported,
  disabled,
  off,
  on,
}

enum AdvertisementTypeArgs {
  connectableUndirected,
  connectableDirected,
  scannableUndirected,
  nonConnectableUndirected,
  scanResponse,
  extended,
}

enum ConnectionStateArgs {
  disconnected,
  connected,
}

/// Windows の `DevicePairingProtectionLevel` をそのまま写したもの。
///
/// pair で要求する保護レベル。装置側のセキュリティ要求(暗号化必須の
/// GATT 等)に合わせてセントラル側からも同じ水準を要求するための口。
/// `defaultLevel` は OS に適切なレベルを選ばせる。
enum DevicePairingProtectionLevelArgs {
  defaultLevel,
  none,
  encryption,
  encryptionAndAuthentication,
}

/// Windows の `DevicePairingResultStatus` をそのまま写したもの。
///
/// 文字列へ潰さず列挙で返すことで、呼び出し側が
/// 「利用者がキャンセルした」「認証がタイムアウトした」「拒否された」を
/// 区別できる。
enum DevicePairingResultStatusArgs {
  paired,
  notReadyToPair,
  notPaired,
  alreadyPaired,
  connectionRejected,
  tooManyConnections,
  hardwareFailure,
  authenticationTimeout,
  authenticationNotAllowed,
  authenticationFailure,
  noSupportedProfiles,
  protectionLevelCouldNotBeMet,
  accessDenied,
  invalidCeremonyData,
  pairingCanceled,
  operationAlreadyInProgress,
  requiredHandlerNotRegistered,
  rejectedByHandler,
  remoteDeviceHasAssociation,
  failed,
}

enum GATTCharacteristicPropertyArgs {
  read,
  write,
  writeWithoutResponse,
  notify,
  indicate,
}

enum GATTCharacteristicWriteTypeArgs {
  withResponse,
  withoutResponse,
}

enum GATTCharacteristicNotifyStateArgs {
  none,
  notify,
  indicate,
}

enum GATTProtectionLevelArgs {
  plain,
  authenticationRequired,
  entryptionRequired,
  encryptionAndAuthenticationRequired,
}

enum GATTProtocolErrorArgs {
  invalidHandle,
  readNotPermitted,
  writeNotPermitted,
  invalidPDU,
  insufficientAuthentication,
  requestNotSupported,
  invalidOffset,
  insufficientAuthorization,
  prepareQueueFull,
  attributeNotFound,
  attributeNotLong,
  insufficientEncryptionKeySize,
  invalidAttributeValueLength,
  unlikelyError,
  insufficientEncryption,
  unsupportedGroupType,
  insufficientResources,
}

enum CacheModeArgs {
  cached,
  uncached,
}

class ManufacturerSpecificDataArgs {
  ManufacturerSpecificDataArgs({
    required this.idArgs,
    required this.dataArgs,
  });

  int idArgs;

  Uint8List dataArgs;

  List<Object?> _toList() {
    return <Object?>[
      idArgs,
      dataArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ManufacturerSpecificDataArgs decode(Object result) {
    result as List<Object?>;
    return ManufacturerSpecificDataArgs(
      idArgs: result[0]! as int,
      dataArgs: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ManufacturerSpecificDataArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AdvertisementArgs {
  AdvertisementArgs({
    this.nameArgs,
    required this.serviceUUIDsArgs,
    required this.serviceDataArgs,
    required this.manufacturerSpecificDataArgs,
  });

  String? nameArgs;

  List<String> serviceUUIDsArgs;

  Map<String, Uint8List> serviceDataArgs;

  List<ManufacturerSpecificDataArgs> manufacturerSpecificDataArgs;

  List<Object?> _toList() {
    return <Object?>[
      nameArgs,
      serviceUUIDsArgs,
      serviceDataArgs,
      manufacturerSpecificDataArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AdvertisementArgs decode(Object result) {
    result as List<Object?>;
    return AdvertisementArgs(
      nameArgs: result[0] as String?,
      serviceUUIDsArgs: (result[1] as List<Object?>?)!.cast<String>(),
      serviceDataArgs: (result[2] as Map<Object?, Object?>?)!.cast<String, Uint8List>(),
      manufacturerSpecificDataArgs: (result[3] as List<Object?>?)!.cast<ManufacturerSpecificDataArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AdvertisementArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class CentralArgs {
  CentralArgs({
    required this.addressArgs,
  });

  int addressArgs;

  List<Object?> _toList() {
    return <Object?>[
      addressArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static CentralArgs decode(Object result) {
    result as List<Object?>;
    return CentralArgs(
      addressArgs: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CentralArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PeripheralArgs {
  PeripheralArgs({
    required this.addressArgs,
  });

  int addressArgs;

  List<Object?> _toList() {
    return <Object?>[
      addressArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static PeripheralArgs decode(Object result) {
    result as List<Object?>;
    return PeripheralArgs(
      addressArgs: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PeripheralArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GATTDescriptorArgs {
  GATTDescriptorArgs({
    required this.handleArgs,
    required this.uuidArgs,
  });

  int handleArgs;

  String uuidArgs;

  List<Object?> _toList() {
    return <Object?>[
      handleArgs,
      uuidArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTDescriptorArgs decode(Object result) {
    result as List<Object?>;
    return GATTDescriptorArgs(
      handleArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTDescriptorArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GATTCharacteristicArgs {
  GATTCharacteristicArgs({
    required this.handleArgs,
    required this.uuidArgs,
    required this.propertyNumbersArgs,
    required this.descriptorsArgs,
  });

  int handleArgs;

  String uuidArgs;

  List<int> propertyNumbersArgs;

  List<GATTDescriptorArgs> descriptorsArgs;

  List<Object?> _toList() {
    return <Object?>[
      handleArgs,
      uuidArgs,
      propertyNumbersArgs,
      descriptorsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTCharacteristicArgs decode(Object result) {
    result as List<Object?>;
    return GATTCharacteristicArgs(
      handleArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      propertyNumbersArgs: (result[2] as List<Object?>?)!.cast<int>(),
      descriptorsArgs: (result[3] as List<Object?>?)!.cast<GATTDescriptorArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTCharacteristicArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GATTServiceArgs {
  GATTServiceArgs({
    required this.handleArgs,
    required this.uuidArgs,
    required this.isPrimaryArgs,
    required this.includedServicesArgs,
    required this.characteristicsArgs,
  });

  int handleArgs;

  String uuidArgs;

  bool isPrimaryArgs;

  List<GATTServiceArgs> includedServicesArgs;

  List<GATTCharacteristicArgs> characteristicsArgs;

  List<Object?> _toList() {
    return <Object?>[
      handleArgs,
      uuidArgs,
      isPrimaryArgs,
      includedServicesArgs,
      characteristicsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTServiceArgs decode(Object result) {
    result as List<Object?>;
    return GATTServiceArgs(
      handleArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      isPrimaryArgs: result[2]! as bool,
      includedServicesArgs: (result[3] as List<Object?>?)!.cast<GATTServiceArgs>(),
      characteristicsArgs: (result[4] as List<Object?>?)!.cast<GATTCharacteristicArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTServiceArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MutableGATTDescriptorArgs {
  MutableGATTDescriptorArgs({
    required this.hashCodeArgs,
    required this.uuidArgs,
    this.valueArgs,
    this.readProtectionLevelArgs,
    this.writeProtectionLevelArgs,
  });

  int hashCodeArgs;

  String uuidArgs;

  Uint8List? valueArgs;

  GATTProtectionLevelArgs? readProtectionLevelArgs;

  GATTProtectionLevelArgs? writeProtectionLevelArgs;

  List<Object?> _toList() {
    return <Object?>[
      hashCodeArgs,
      uuidArgs,
      valueArgs,
      readProtectionLevelArgs,
      writeProtectionLevelArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableGATTDescriptorArgs decode(Object result) {
    result as List<Object?>;
    return MutableGATTDescriptorArgs(
      hashCodeArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      valueArgs: result[2] as Uint8List?,
      readProtectionLevelArgs: result[3] as GATTProtectionLevelArgs?,
      writeProtectionLevelArgs: result[4] as GATTProtectionLevelArgs?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableGATTDescriptorArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MutableGATTCharacteristicArgs {
  MutableGATTCharacteristicArgs({
    required this.hashCodeArgs,
    required this.uuidArgs,
    this.valueArgs,
    required this.propertyNumbersArgs,
    this.readProtectionLevelArgs,
    this.writeProtectionLevelArgs,
    required this.descriptorsArgs,
  });

  int hashCodeArgs;

  String uuidArgs;

  Uint8List? valueArgs;

  List<int> propertyNumbersArgs;

  GATTProtectionLevelArgs? readProtectionLevelArgs;

  GATTProtectionLevelArgs? writeProtectionLevelArgs;

  List<MutableGATTDescriptorArgs> descriptorsArgs;

  List<Object?> _toList() {
    return <Object?>[
      hashCodeArgs,
      uuidArgs,
      valueArgs,
      propertyNumbersArgs,
      readProtectionLevelArgs,
      writeProtectionLevelArgs,
      descriptorsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableGATTCharacteristicArgs decode(Object result) {
    result as List<Object?>;
    return MutableGATTCharacteristicArgs(
      hashCodeArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      valueArgs: result[2] as Uint8List?,
      propertyNumbersArgs: (result[3] as List<Object?>?)!.cast<int>(),
      readProtectionLevelArgs: result[4] as GATTProtectionLevelArgs?,
      writeProtectionLevelArgs: result[5] as GATTProtectionLevelArgs?,
      descriptorsArgs: (result[6] as List<Object?>?)!.cast<MutableGATTDescriptorArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableGATTCharacteristicArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MutableGATTServiceArgs {
  MutableGATTServiceArgs({
    required this.hashCodeArgs,
    required this.uuidArgs,
    required this.isPrimaryArgs,
    required this.includedServicesArgs,
    required this.characteristicsArgs,
  });

  int hashCodeArgs;

  String uuidArgs;

  bool isPrimaryArgs;

  List<MutableGATTServiceArgs> includedServicesArgs;

  List<MutableGATTCharacteristicArgs> characteristicsArgs;

  List<Object?> _toList() {
    return <Object?>[
      hashCodeArgs,
      uuidArgs,
      isPrimaryArgs,
      includedServicesArgs,
      characteristicsArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static MutableGATTServiceArgs decode(Object result) {
    result as List<Object?>;
    return MutableGATTServiceArgs(
      hashCodeArgs: result[0]! as int,
      uuidArgs: result[1]! as String,
      isPrimaryArgs: result[2]! as bool,
      includedServicesArgs: (result[3] as List<Object?>?)!.cast<MutableGATTServiceArgs>(),
      characteristicsArgs: (result[4] as List<Object?>?)!.cast<MutableGATTCharacteristicArgs>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MutableGATTServiceArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GATTReadRequestArgs {
  GATTReadRequestArgs({
    required this.idArgs,
    required this.offsetArgs,
    required this.lengthArgs,
  });

  int idArgs;

  int offsetArgs;

  int lengthArgs;

  List<Object?> _toList() {
    return <Object?>[
      idArgs,
      offsetArgs,
      lengthArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTReadRequestArgs decode(Object result) {
    result as List<Object?>;
    return GATTReadRequestArgs(
      idArgs: result[0]! as int,
      offsetArgs: result[1]! as int,
      lengthArgs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTReadRequestArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GATTWriteRequestArgs {
  GATTWriteRequestArgs({
    required this.idArgs,
    required this.offsetArgs,
    required this.valueArgs,
    required this.typeArgs,
  });

  int idArgs;

  int offsetArgs;

  Uint8List valueArgs;

  GATTCharacteristicWriteTypeArgs typeArgs;

  List<Object?> _toList() {
    return <Object?>[
      idArgs,
      offsetArgs,
      valueArgs,
      typeArgs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GATTWriteRequestArgs decode(Object result) {
    result as List<Object?>;
    return GATTWriteRequestArgs(
      idArgs: result[0]! as int,
      offsetArgs: result[1]! as int,
      valueArgs: result[2]! as Uint8List,
      typeArgs: result[3]! as GATTCharacteristicWriteTypeArgs,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GATTWriteRequestArgs || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BluetoothLowEnergyStateArgs) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AdvertisementTypeArgs) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ConnectionStateArgs) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is DevicePairingProtectionLevelArgs) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is DevicePairingResultStatusArgs) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is GATTCharacteristicPropertyArgs) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is GATTCharacteristicWriteTypeArgs) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is GATTCharacteristicNotifyStateArgs) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is GATTProtectionLevelArgs) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is GATTProtocolErrorArgs) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is CacheModeArgs) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is ManufacturerSpecificDataArgs) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is AdvertisementArgs) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is CentralArgs) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is PeripheralArgs) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is GATTDescriptorArgs) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is GATTCharacteristicArgs) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is GATTServiceArgs) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is MutableGATTDescriptorArgs) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is MutableGATTCharacteristicArgs) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is MutableGATTServiceArgs) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is GATTReadRequestArgs) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is GATTWriteRequestArgs) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BluetoothLowEnergyStateArgs.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : AdvertisementTypeArgs.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ConnectionStateArgs.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DevicePairingProtectionLevelArgs.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DevicePairingResultStatusArgs.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GATTCharacteristicPropertyArgs.values[value];
      case 135: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GATTCharacteristicWriteTypeArgs.values[value];
      case 136: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GATTCharacteristicNotifyStateArgs.values[value];
      case 137: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GATTProtectionLevelArgs.values[value];
      case 138: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GATTProtocolErrorArgs.values[value];
      case 139: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CacheModeArgs.values[value];
      case 140: 
        return ManufacturerSpecificDataArgs.decode(readValue(buffer)!);
      case 141: 
        return AdvertisementArgs.decode(readValue(buffer)!);
      case 142: 
        return CentralArgs.decode(readValue(buffer)!);
      case 143: 
        return PeripheralArgs.decode(readValue(buffer)!);
      case 144: 
        return GATTDescriptorArgs.decode(readValue(buffer)!);
      case 145: 
        return GATTCharacteristicArgs.decode(readValue(buffer)!);
      case 146: 
        return GATTServiceArgs.decode(readValue(buffer)!);
      case 147: 
        return MutableGATTDescriptorArgs.decode(readValue(buffer)!);
      case 148: 
        return MutableGATTCharacteristicArgs.decode(readValue(buffer)!);
      case 149: 
        return MutableGATTServiceArgs.decode(readValue(buffer)!);
      case 150: 
        return GATTReadRequestArgs.decode(readValue(buffer)!);
      case 151: 
        return GATTWriteRequestArgs.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CentralManagerHostApi {
  /// Constructor for [CentralManagerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CentralManagerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<BluetoothLowEnergyStateArgs> getState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BluetoothLowEnergyStateArgs?)!;
    }
  }

  Future<void> startDiscovery(List<String> serviceUUIDsArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.startDiscovery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUUIDsArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopDiscovery() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.stopDiscovery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> connect(int addressArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disconnect(int addressArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> getMTU(int addressArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getMTU$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<List<GATTServiceArgs>> getServices(int addressArgs, CacheModeArgs modeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getServices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, modeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<GATTServiceArgs>();
    }
  }

  Future<List<GATTServiceArgs>> getIncludedServices(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getIncludedServices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<GATTServiceArgs>();
    }
  }

  Future<List<GATTCharacteristicArgs>> getCharacteristics(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getCharacteristics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<GATTCharacteristicArgs>();
    }
  }

  Future<List<GATTDescriptorArgs>> getDescriptors(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.getDescriptors$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<GATTDescriptorArgs>();
    }
  }

  Future<Uint8List> readCharacteristic(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.readCharacteristic$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?)!;
    }
  }

  Future<void> writeCharacteristic(int addressArgs, int handleArgs, Uint8List valueArgs, GATTCharacteristicWriteTypeArgs typeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.writeCharacteristic$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, valueArgs, typeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setCharacteristicNotifyState(int addressArgs, int handleArgs, GATTCharacteristicNotifyStateArgs stateArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.setCharacteristicNotifyState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, stateArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 特性への無線通信に要求する GATT セキュリティ
  /// (`GattCharacteristic.ProtectionLevel`)を設定する。
  ///
  /// 設定後にその特性へ read/write すると、スタックは要求水準を満たす
  /// リンク(暗号化等)を操作の前提として確立しようとする。装置側の
  /// セキュリティ要求と一致させることで、ATT エラー(0x0F 等)を起点と
  /// した事後の再試行ではなく、OS 主導の事前確立に切り替えられる。
  Future<void> setCharacteristicProtectionLevel(int addressArgs, int handleArgs, GATTProtectionLevelArgs levelArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.setCharacteristicProtectionLevel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, levelArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Uint8List> readDescriptor(int addressArgs, int handleArgs, CacheModeArgs modeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.readDescriptor$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, modeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?)!;
    }
  }

  Future<void> writeDescriptor(int addressArgs, int handleArgs, Uint8List valueArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.writeDescriptor$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, handleArgs, valueArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// ペアリング(暗号化リンクの確立)を開始し、結果が出るまで待つ。
  ///
  /// 保護された属性は、リンクが暗号化されていないと読み書きできない。
  /// ボンディングしない装置では鍵が保存されないため、**接続ごとに**
  /// これを済ませてから初期読み出しへ進む必要がある。
  ///
  /// デスクトップでは同意は必ずシステムダイアログで行われ、アプリからは
  /// 抑止できない(Microsoft の文書と実測の両方で確認)。アプリ側の
  /// PairingRequested ハンドラは、ConfirmOnly を受理するために常に登録する
  /// (登録しないと RequiredHandlerNotRegistered / RejectedByHandler で
  /// 失敗する)。つまり「自動承認するか」という選択肢は存在しない。
  ///
  /// 失敗を例外にせず結果として返すので、キャンセル・タイムアウト・拒否を
  /// 呼び出し側で区別できる。
  ///
  /// [protectionLevelArgs] は要求する保護レベル。装置側のセキュリティ要求に
  /// 合わせて指定する(未ペアリング機器の `Pairing().ProtectionLevel()` は
  /// 「現在の水準 = None」を返すだけで要求水準ではないため、ここで明示する)。
  Future<DevicePairingResultStatusArgs> pair(int addressArgs, DevicePairingProtectionLevelArgs protectionLevelArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.pair$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, protectionLevelArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DevicePairingResultStatusArgs?)!;
    }
  }

  /// OS が保持しているペアリング(関連付け)を解除する。接続は不要。
  Future<void> unpair(int addressArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.unpair$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// OS がこの装置をペアリング済みとみなしているか。接続は不要。
  ///
  /// WinRT はプラットフォームスレッド(STA)でのブロック待ちを禁じているため、
  /// 同期メソッドにはできない(`.get()` が `!is_sta_thread()` で落ちる)。
  Future<bool> isPaired(int addressArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerHostApi.isPaired$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

abstract class CentralManagerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStateChanged(BluetoothLowEnergyStateArgs stateArgs);

  void onDiscovered(PeripheralArgs peripheralArgs, int rssiArgs, int timestampArgs, AdvertisementTypeArgs typeArgs, AdvertisementArgs advertisementArgs);

  void onConnectionStateChanged(PeripheralArgs peripheralArgs, ConnectionStateArgs stateArgs);

  void onMTUChanged(PeripheralArgs peripheralArgs, int mtuArgs);

  void onCharacteristicNotified(PeripheralArgs peripheralArgs, GATTCharacteristicArgs characteristicArgs, Uint8List valueArgs);

  /// ネイティブ層の診断メッセージ。Dart 側の logger(info)へ中継する。
  ///
  /// ネイティブには独自のログ機構が無いため、調査時の観測値
  /// (例: ペアリングの保護レベル・儀式の発火有無)はこの口で表出する。
  void onLogged(String messageArgs);

  static void setUp(CentralManagerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BluetoothLowEnergyStateArgs? arg_stateArgs = (args[0] as BluetoothLowEnergyStateArgs?);
          assert(arg_stateArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onStateChanged was null, expected non-null BluetoothLowEnergyStateArgs.');
          try {
            api.onStateChanged(arg_stateArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PeripheralArgs? arg_peripheralArgs = (args[0] as PeripheralArgs?);
          assert(arg_peripheralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered was null, expected non-null PeripheralArgs.');
          final int? arg_rssiArgs = (args[1] as int?);
          assert(arg_rssiArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered was null, expected non-null int.');
          final int? arg_timestampArgs = (args[2] as int?);
          assert(arg_timestampArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered was null, expected non-null int.');
          final AdvertisementTypeArgs? arg_typeArgs = (args[3] as AdvertisementTypeArgs?);
          assert(arg_typeArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered was null, expected non-null AdvertisementTypeArgs.');
          final AdvertisementArgs? arg_advertisementArgs = (args[4] as AdvertisementArgs?);
          assert(arg_advertisementArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onDiscovered was null, expected non-null AdvertisementArgs.');
          try {
            api.onDiscovered(arg_peripheralArgs!, arg_rssiArgs!, arg_timestampArgs!, arg_typeArgs!, arg_advertisementArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onConnectionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onConnectionStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PeripheralArgs? arg_peripheralArgs = (args[0] as PeripheralArgs?);
          assert(arg_peripheralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onConnectionStateChanged was null, expected non-null PeripheralArgs.');
          final ConnectionStateArgs? arg_stateArgs = (args[1] as ConnectionStateArgs?);
          assert(arg_stateArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onConnectionStateChanged was null, expected non-null ConnectionStateArgs.');
          try {
            api.onConnectionStateChanged(arg_peripheralArgs!, arg_stateArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onMTUChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onMTUChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PeripheralArgs? arg_peripheralArgs = (args[0] as PeripheralArgs?);
          assert(arg_peripheralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onMTUChanged was null, expected non-null PeripheralArgs.');
          final int? arg_mtuArgs = (args[1] as int?);
          assert(arg_mtuArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onMTUChanged was null, expected non-null int.');
          try {
            api.onMTUChanged(arg_peripheralArgs!, arg_mtuArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onCharacteristicNotified$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onCharacteristicNotified was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PeripheralArgs? arg_peripheralArgs = (args[0] as PeripheralArgs?);
          assert(arg_peripheralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onCharacteristicNotified was null, expected non-null PeripheralArgs.');
          final GATTCharacteristicArgs? arg_characteristicArgs = (args[1] as GATTCharacteristicArgs?);
          assert(arg_characteristicArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onCharacteristicNotified was null, expected non-null GATTCharacteristicArgs.');
          final Uint8List? arg_valueArgs = (args[2] as Uint8List?);
          assert(arg_valueArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onCharacteristicNotified was null, expected non-null Uint8List.');
          try {
            api.onCharacteristicNotified(arg_peripheralArgs!, arg_characteristicArgs!, arg_valueArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onLogged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onLogged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_messageArgs = (args[0] as String?);
          assert(arg_messageArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.CentralManagerFlutterApi.onLogged was null, expected non-null String.');
          try {
            api.onLogged(arg_messageArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class PeripheralManagerHostApi {
  /// Constructor for [PeripheralManagerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PeripheralManagerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<BluetoothLowEnergyStateArgs> getState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.getState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BluetoothLowEnergyStateArgs?)!;
    }
  }

  Future<void> addService(MutableGATTServiceArgs serviceArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.addService$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> removeService(int hashCodeArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.removeService$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[hashCodeArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startAdvertising(AdvertisementArgs advertisementArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.startAdvertising$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[advertisementArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopAdvertising() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.stopAdvertising$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> getMaxNotificationSize(int addressArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.getMaxNotificationSize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> respondReadRequestWithValue(int idArgs, Uint8List valueArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondReadRequestWithValue$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs, valueArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> respondReadRequestWithProtocolError(int idArgs, GATTProtocolErrorArgs errorArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondReadRequestWithProtocolError$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs, errorArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> respondWriteRequest(int idArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondWriteRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> respondWriteRequestWithProtocolError(int idArgs, GATTProtocolErrorArgs errorArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.respondWriteRequestWithProtocolError$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[idArgs, errorArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> notifyValue(int addressArgs, int hashCodeArgs, Uint8List valueArgs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerHostApi.notifyValue$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[addressArgs, hashCodeArgs, valueArgs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class PeripheralManagerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStateChanged(BluetoothLowEnergyStateArgs stateArgs);

  void onMTUChanged(CentralArgs centralArgs, int mtuArgs);

  void onCharacteristicReadRequest(CentralArgs centralArgs, int hashCodeArgs, GATTReadRequestArgs requestArgs);

  void onCharacteristicWriteRequest(CentralArgs centralArgs, int hashCodeArgs, GATTWriteRequestArgs requestArgs);

  void onCharacteristicSubscribedClientsChanged(int hashCodeArgs, List<CentralArgs> centralsArgs);

  void onDescriptorReadRequest(CentralArgs centralArgs, int hashCodeArgs, GATTReadRequestArgs requestArgs);

  void onDescriptorWriteRequest(CentralArgs centralArgs, int hashCodeArgs, GATTWriteRequestArgs requestArgs);

  static void setUp(PeripheralManagerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BluetoothLowEnergyStateArgs? arg_stateArgs = (args[0] as BluetoothLowEnergyStateArgs?);
          assert(arg_stateArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onStateChanged was null, expected non-null BluetoothLowEnergyStateArgs.');
          try {
            api.onStateChanged(arg_stateArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onMTUChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onMTUChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CentralArgs? arg_centralArgs = (args[0] as CentralArgs?);
          assert(arg_centralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onMTUChanged was null, expected non-null CentralArgs.');
          final int? arg_mtuArgs = (args[1] as int?);
          assert(arg_mtuArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onMTUChanged was null, expected non-null int.');
          try {
            api.onMTUChanged(arg_centralArgs!, arg_mtuArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicReadRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicReadRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CentralArgs? arg_centralArgs = (args[0] as CentralArgs?);
          assert(arg_centralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicReadRequest was null, expected non-null CentralArgs.');
          final int? arg_hashCodeArgs = (args[1] as int?);
          assert(arg_hashCodeArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicReadRequest was null, expected non-null int.');
          final GATTReadRequestArgs? arg_requestArgs = (args[2] as GATTReadRequestArgs?);
          assert(arg_requestArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicReadRequest was null, expected non-null GATTReadRequestArgs.');
          try {
            api.onCharacteristicReadRequest(arg_centralArgs!, arg_hashCodeArgs!, arg_requestArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicWriteRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicWriteRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CentralArgs? arg_centralArgs = (args[0] as CentralArgs?);
          assert(arg_centralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicWriteRequest was null, expected non-null CentralArgs.');
          final int? arg_hashCodeArgs = (args[1] as int?);
          assert(arg_hashCodeArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicWriteRequest was null, expected non-null int.');
          final GATTWriteRequestArgs? arg_requestArgs = (args[2] as GATTWriteRequestArgs?);
          assert(arg_requestArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicWriteRequest was null, expected non-null GATTWriteRequestArgs.');
          try {
            api.onCharacteristicWriteRequest(arg_centralArgs!, arg_hashCodeArgs!, arg_requestArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicSubscribedClientsChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicSubscribedClientsChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_hashCodeArgs = (args[0] as int?);
          assert(arg_hashCodeArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicSubscribedClientsChanged was null, expected non-null int.');
          final List<CentralArgs>? arg_centralsArgs = (args[1] as List<Object?>?)?.cast<CentralArgs>();
          assert(arg_centralsArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onCharacteristicSubscribedClientsChanged was null, expected non-null List<CentralArgs>.');
          try {
            api.onCharacteristicSubscribedClientsChanged(arg_hashCodeArgs!, arg_centralsArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorReadRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorReadRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CentralArgs? arg_centralArgs = (args[0] as CentralArgs?);
          assert(arg_centralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorReadRequest was null, expected non-null CentralArgs.');
          final int? arg_hashCodeArgs = (args[1] as int?);
          assert(arg_hashCodeArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorReadRequest was null, expected non-null int.');
          final GATTReadRequestArgs? arg_requestArgs = (args[2] as GATTReadRequestArgs?);
          assert(arg_requestArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorReadRequest was null, expected non-null GATTReadRequestArgs.');
          try {
            api.onDescriptorReadRequest(arg_centralArgs!, arg_hashCodeArgs!, arg_requestArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorWriteRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorWriteRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CentralArgs? arg_centralArgs = (args[0] as CentralArgs?);
          assert(arg_centralArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorWriteRequest was null, expected non-null CentralArgs.');
          final int? arg_hashCodeArgs = (args[1] as int?);
          assert(arg_hashCodeArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorWriteRequest was null, expected non-null int.');
          final GATTWriteRequestArgs? arg_requestArgs = (args[2] as GATTWriteRequestArgs?);
          assert(arg_requestArgs != null,
              'Argument for dev.flutter.pigeon.bluetooth_low_energy_windows.PeripheralManagerFlutterApi.onDescriptorWriteRequest was null, expected non-null GATTWriteRequestArgs.');
          try {
            api.onDescriptorWriteRequest(arg_centralArgs!, arg_hashCodeArgs!, arg_requestArgs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
